title: CiscoDude.net
description: "A tech blog by Theo Baschak. Often updates on topics like: Internet, BGP, Networking, Security, and personal projects."
author: Theodore Baschak
github: https://github.com/tbaschak
about: "BOFH. Open Source Guru. Founder/Operator of Hextet Systems, AS395089 and Network Architect for Daemon Defense Systems, AS55101."
#disqus_shortname: stackproblems
google_analytics: UA-46747597-1
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/tbaschak"
    - icon: fa-twitter
      link: "https://twitter.com/TheodoreBaschak"
    - icon: fa-linkedin
      link: "https://ca.linkedin.com/in/theodore-baschak-70442960"
    - icon: fa-flickr
      link: "https://www.flickr.com/photos/theodorebaschak"
    - icon: fa-instagram
      link: "https://www.instagram.com/theodorebaschak/"

share:
  twitter_username: TheodoreBaschak
  fb_appid: 987401608025174

urls:
    - text: About Me
      url: /about/
    - text: Canadian BGP
      url: /bgp/
    - text: MB BGP Status
      url: /bgp/mb/
    - text: SK BGP Status
      url: /bgp/sk/
    - text: CheatSheets
      url: "https://cheatsheets.ciscodude.net/"
    - text: Presentations
      url: /presentations/
    - text: Projects
      url: /projects/
    - text: Contact
      url: /contact/


url: "https://ciscodude.net"
baseurl: ""
paginate: 30
per_page: 30
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
#  - jekyll-gist
  - octopress-gist
  - jekyll-twitter-plugin
  - jekyll-youtube

exclude: [vendor]

permalink: /:year/:month/:day/:title/

twitter:
  consumer_key: BXmupxKyPRRKYR7E2oDd3BM5W
  consumer_secret: DulWBWQ2u1L7m3brqcOUuOLIRazGuZft9uiCGQVbVbvwcpden8
  access_token: 371307426-TxZbhCShYNZ0Z0fhbzajd9CvIuWrfgrRb8pZEXun
  access_token_secret: hVeZw8l20nQlNKTNvYOxWVsPHiJ9YQIsIaPvBM8vzeH7P

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
